### ISSUE TITLE
1Inch sync error handling

### ISSUE THREAD

**Issue by Addminus** [lifinance/lifi-web#10]
getting quotes and swap information from 1Inch might fail with "cannot sync to token 0x..."

On the server, this issue is handled by not return routes.

There is no handling on the front end. Immediately retriggering the swap might not work. The sync issue might take a while to resolve itself.

**Comment by maxklenk** [comment]
I improved the routes handling on server side. Different routes can now fail independent of each other and only the successful ones are returned to the client.
