### ISSUE TITLE
xPollinate Optimizations

### ISSUE THREAD

**Issue by maxklenk** [lifinance/lifi-web#21]
Optimizations:
- [ ] add walletConnect support, eg. using https://docs.blocknative.com/onboard# (https://github.com/lifinance/lifi-web/pull/22)
- [ ] (wait for https://github.com/connext/nxtp/issues/306)Show error of `Liquidity Unavailable` on UI if the transaction quote errors `No bid available` - it shares some helpful insight in error context.
- [x] show errors if step fail
- [ ] hide failed transfers from active transactions list
- [ ] find replaced transaction (eg. speedup)
- [x] show tx confirmations on the sender prepare and receiver prepares 
- [x] update listeners in nxtp.tsx to check transaction_id and listen to multiple events (to handle multiple transactions in parallel)
- [ ] toggle active/historic transactions by clicking the small arrow
- [ ] show warning if receiving address different to the own address is set
- [ ] save options in local storage
- [ ] ask user to retry signing the signature if finish step takes longer then 5 minutes
- [ ] notify modal if graph returns that the current transfer is already in the finish step
- [ ] rename switch chain button into something like "Change Chain in your wallet to BSC"
- [ ] show new token, balance and add to metamask

Optional:
- [x] (wait for sdk support) avoid multiple messaging sign in
- [ ] connected with unknown network
- [ ] switch connected account / better disconnect
- [ ] serve font from our domain
- [x] show balance and max in form
- [x] check bundle size

**Comment by philippzentner** [comment]
Transferred to Jira
