### ISSUE TITLE
Programmatically add new Chains and Tokens to Metamask Wallet

### ISSUE THREAD

**Issue by Addminus** [lifinance/lifi-web#5]
Add new chains:
https://docs.metamask.io/guide/rpc-api.html#other-rpc-methods
section: wallet_addEthereumChain, wallet_switchEthereumChain

add new Tokens:
https://docs.metamask.io/guide/rpc-api.html#other-rpc-methods
section: wallet_watchAsset

**Comment by philippzentner** [comment]
Transferred to Jira
