### ISSUE TITLE
Auto refresh countdown feature for Swap view

### ISSUE THREAD

**Issue by Addminus** [lifinance/lifi-web#9]
reload transfer routes after x seeconds from the server to guarantee best swapping routes at all times. 

similar to 

https://app.1inch.io/#/1/swap/USDC/DAI

![image](https://user-images.githubusercontent.com/10106351/124894211-bdcb9600-dfdb-11eb-92cc-b98491b8b334.png)

**Comment by philippzentner** [comment]
Transferred to Jira
